from utils import anl_input, joint_anl_output, joint_decode_anl
from evaluate import BatchEvaluator
import torch
import os
import re
from transformers import AutoModelForCausalLM, AutoTokenizer
import json
from tqdm import tqdm
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model_name = "/workspace/saradhi_pg/Nil/llama-experiment/llama-3.1-8b-instruct"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name)
model.to(device)

def generate_output(prompt):
    inputs = tokenizer(prompt, return_tensors="pt").to(device)
    output = model.generate(inputs.input_ids, max_length=8192, num_return_sequences=1, repetition_penalty=1.1, temperature = 0.5)
    explanation = tokenizer.decode(output[0], skip_special_tokens=True)
    return explanation


splits = ['test']
dataset_name = 'cdcp'
num_shots = 10

evaluator = BatchEvaluator()

for split in splits:
    input_filename = f"./datasets/updated_{dataset_name}/updated_{dataset_name}_{split}.json"
    output_filename = f"./few_shot_results/{num_shots}-shot-{dataset_name}.json"

    with open(input_filename, 'r') as f:
        data = json.load(f)

    for idx, item in enumerate(tqdm(data, desc="Processing")):
        unique_id = item["id"]
        paragraph = item['paragraph']
        components = item['components']
        relations = item['relations']

        formatted_input = anl_input (item["paragraph"], item["components"])
        true_output = joint_anl_output (item["paragraph"], item["components"], item["relations"])

        prompt = f"""
### Task: 
Given an argumentatively specified component boundaries enclosed with [ argument span ], classify them with predefined argument types such as ('value', 'fact', 'policy', 'testimony', 'common_ground', 'hypothetical_instance', 'statistics', 'real_example', 'others') and connect the related argument components in the output with this format: [ argument span | type | related argument span ]. Please note, the argument span boundaries must be same for both input and output for all components. Spans must be extractive, not generative. Here are the following examples:

# Example 1:

###Input: [ What I had in mind when I made this comment was that some debtors are in debt because of a medical condition that has negatively impacted their ability to work. ] [ They may be on Social Security disability for this reason. ] [ Sometimes, that medical condition is scientifically known to be aggravated by stress, such as any heart condition, or an anxiety disorder. ] [ Currently, Section 806 of the FDCPA makes abuse or harassment of debtors illegal. ] [ However, what qualifies as abuse might be different for a debtor with a disabling medical condition that is sensitive to stress. ] [ My hope, and my suggestion, is that there could be some way for debtors to make collection agencies aware of the fact that the debtor has a documented medical disability, and that abusive or harassing phone calls have additional health consequences for the debtor. ]

###Output: [ What I had in mind when I made this comment was that some debtors are in debt because of a medical condition that has negatively impacted their ability to work. | value ] [ They may be on Social Security disability for this reason. | value ] [ Sometimes, that medical condition is scientifically known to be aggravated by stress, such as any heart condition, or an anxiety disorder. | fact ] [ Currently, Section 806 of the FDCPA makes abuse or harassment of debtors illegal. | fact ] [ However, what qualifies as abuse might be different for a debtor with a disabling medical condition that is sensitive to stress. | value | My hope, and my suggestion, is that there could be some way for debtors to make collection agencies aware of the fact that the debtor has a documented medical disability, and that abusive or harassing phone calls have additional health consequences for the debtor. ] [ My hope, and my suggestion, is that there could be some way for debtors to make collection agencies aware of the fact that the debtor has a documented medical disability, and that abusive or harassing phone calls have additional health consequences for the debtor. | value ]

# Example 2:

###Input: [ Some years ago, a debt collector was trying to collect a debt for an emergency room visit that included foot/leg xrays. ] [ The problem was that the only time I had ever been to the hospital in question was a worker's compensation covered workplace injury and it involved only my hand (sliced open, six stitches). ] [ I had contacted the collection agency and informed them that I did not owe anything and the circumstances of the visit. ] [ Although that did not work, once I contacted all three credit bureaus with the same information, the debt collector was unable to verify the debt ] [ and they removed it from my credit report - and stopped contacting me. ]

###Output: [ Some years ago, a debt collector was trying to collect a debt for an emergency room visit that included foot/leg xrays. | testimony ] [ The problem was that the only time I had ever been to the hospital in question was a worker's compensation covered workplace injury and it involved only my hand (sliced open, six stitches). | testimony ] [ I had contacted the collection agency and informed them that I did not owe anything and the circumstances of the visit. | testimony ] [ Although that did not work, once I contacted all three credit bureaus with the same information, the debt collector was unable to verify the debt | testimony | and they removed it from my credit report - and stopped contacting me. ] [ and they removed it from my credit report - and stopped contacting me. | testimony ]

# Example 3:

###Input: [ The agency I work for is small and follows FDCPA to the letter of the law. ] [ And yet we are still sued constantly by attorneys representing debtors. ] [ These attorneys count on the fact that it's less costly to settle than to go to court to prove that we have not violated the law. ] [ Our retail division is in trouble ] [ because we've recently lost our two largest clients -- for this reason. ] [ They're now getting slapped with bogus lawsuits as well. ] [ People don't even have to pay their bills any more; ] [ they just send a "cease and desist" letter, hire an attorney, and wait for a settlement to roll in. ] [ All this will lead to are more stringent rules around extending credit, which is not a good thing for the economy. ] [ If we keep going down this slope, the only people who will be able to get credit will be those who don't need it. ]

###Output: [ The agency I work for is small and follows FDCPA to the letter of the law. | value ] [ And yet we are still sued constantly by attorneys representing debtors. | testimony ] [ These attorneys count on the fact that it's less costly to settle than to go to court to prove that we have not violated the law. | value ] [ Our retail division is in trouble | value ] [ because we've recently lost our two largest clients -- for this reason. | testimony | Our retail division is in trouble ] [ They're now getting slapped with bogus lawsuits as well. | value ] [ People don't even have to pay their bills any more; | value ] [ they just send a "cease and desist" letter, hire an attorney, and wait for a settlement to roll in. | value ] [ All this will lead to are more stringent rules around extending credit, which is not a good thing for the economy. | value ] [ If we keep going down this slope, the only people who will be able to get credit will be those who don't need it. | value ]

# Example 4:

###Input: [ I too am a family member of a consumer who claims to have paid his debt of 12 - 15 years ago, ][ but my husband and I receive two or three calls a day asking for him to call various agencies about a "matter" with a case #. ][ In one instance they said they would be at the door in one hour. ][ This family member has not lived here for about 16 years. ][ They should not be allowed to call anyone other than the debtor who nowadays can be found on the internet!!! ]

###Output: [ I too am a family member of a consumer who claims to have paid his debt of 12 - 15 years ago, | testimony | They should not be allowed to call anyone other than the debtor who nowadays can be found on the internet!!! ][ but my husband and I receive two or three calls a day asking for him to call various agencies about a "matter" with a case #. | testimony ][ In one instance they said they would be at the door in one hour. | testimony ][ This family member has not lived here for about 16 years. | testimony ][ They should not be allowed to call anyone other than the debtor who nowadays can be found on the internet!!! | policy ]

# Example 5:

###Input: [ The current validation notice is already too long--bordering on "boilerplate". ] [ To add more language to this would confuse or intimidate the least sophisticated debtor and/or lead them to immediately ask that the creditor cease communication. ] [ The problem with that strategy is that it forces the creditor to file suit, thereby incurring court costs that will be added to the debt. ] [ Instead, debtors should be encouraged to communicate their questions & concerns to the collector who can then (after right-party verification) openly discuss the account & quite possibly answer the debtor's question(s). ]

###Output: [ The current validation notice is already too long--bordering on "boilerplate". | value ] [ To add more language to this would confuse or intimidate the least sophisticated debtor and/or lead them to immediately ask that the creditor cease communication. | value ] [ The problem with that strategy is that it forces the creditor to file suit, thereby incurring court costs that will be added to the debt. | value ] [ Instead, debtors should be encouraged to communicate their questions & concerns to the collector who can then (after right-party verification) openly discuss the account & quite possibly answer the debtor's question(s). | policy ]

Example 6:

###Input: [ I think that the CFPB should come up with a regulation that prohibits a creditor, and a debt collector, from sending the debt for collection to another debt collection company AFTER a consumer disputes the debt, or sends a "cease and desist" letter to the debt collection agency. ] [ In my cases that I worked on, a "cease and desist" letter was sent to both the debt collector and original creditor requesting that they cease collecting the debt as per the FDCPA. However, all they do is close out one debt collection company and send the account to another one. Then the consumer has to repeat the process. ] [ The CFPB should come up with a regulation that states once the debt is disputed or a "cease and desist" letter is sent to the debt collector, THAT debt collector must advise the original creditor that a C&D letter was sent. ]

###Output: [ I think that the CFPB should come up with a regulation that prohibits a creditor, and a debt collector, from sending the debt for collection to another debt collection company AFTER a consumer disputes the debt, or sends a "cease and desist" letter to the debt collection agency. | policy | The CFPB should come up with a regulation that states once the debt is disputed or a "cease and desist" letter is sent to the debt collector, THAT debt collector must advise the original creditor that a C&D letter was sent. ] [ In my cases that I worked on, a "cease and desist" letter was sent to both the debt collector and original creditor requesting that they cease collecting the debt as per the FDCPA. However, all they do is close out one debt collection company and send the account to another one. Then the consumer has to repeat the process. | value | I think that the CFPB should come up with a regulation that prohibits a creditor, and a debt collector, from sending the debt for collection to another debt collection company AFTER a consumer disputes the debt, or sends a "cease and desist" letter to the debt collection agency. | The CFPB should come up with a regulation that states once the debt is disputed or a "cease and desist" letter is sent to the debt collector, THAT debt collector must advise the original creditor that a C&D letter was sent. ] [ The CFPB should come up with a regulation that states once the debt is disputed or a "cease and desist" letter is sent to the debt collector, THAT debt collector must advise the original creditor that a C&D letter was sent. | policy ]

Example 7:

###Input: [ When two parties engage in a lawsuit, each side presents the evidence they have supporting their assertions. ] [ As a collector, I provide proof of the debt ] [ The debtor is also expected to present some proof that the debt is not theirs. ] [ Yes, the assumption is innocent until proven guilty but you have to provide evidence to support your claim of innocence. ] [ If I offer a signed document that says you agreed to the purchase and documentation that supports that you did not pay, I have fulfilled my side of the burden of proof. ] [ The debtor also bears a burden of proof in our system. ] [ That's what the judge is for - to hear both sides, weigh the evidence, and make a fair decision based on the evidence and arguments presented. ]

###Output: [ When two parties engage in a lawsuit, each side presents the evidence they have supporting their assertions. | fact ] [ As a collector, I provide proof of the debt | testimony ] [ The debtor is also expected to present some proof that the debt is not theirs. | fact ] [ Yes, the assumption is innocent until proven guilty but you have to provide evidence to support your claim of innocence. | fact ] [ If I offer a signed document that says you agreed to the purchase and documentation that supports that you did not pay, I have fulfilled my side of the burden of proof. | fact ] [ The debtor also bears a burden of proof in our system. | fact ] [ That's what the judge is for - to hear both sides, weigh the evidence, and make a fair decision based on the evidence and arguments presented. | value ]

Example 8:

###Input: [ while this isn't the best forum for me to go into my company's entire collection process, we work a debt for at least 120 days with letters, live agent calls, robo calls, emails, mailed invoices, and by suspending subscription service (where allowed) as part of our collection campaign. ] [ Even then, we only go to litigation after the debtor has been unresponsive to our attempts to contact them. ] [ I've found that if a debtor talks to their creditors, many times creditors will take their situation into account. ] [ I've offered lengthy repayment plans, reduced or waived interest or late fees, or partial settlement for those explain their hardship. ] [ But if a debtor is uncooperative or doesn't respond to our attempts to work out a balance, what other alternatives do creditors have? ]

###Output: [ while this isn't the best forum for me to go into my company's entire collection process, we work a debt for at least 120 days with letters, live agent calls, robo calls, emails, mailed invoices, and by suspending subscription service (where allowed) as part of our collection campaign. | testimony ] [ Even then, we only go to litigation after the debtor has been unresponsive to our attempts to contact them. | testimony ] [ I've found that if a debtor talks to their creditors, many times creditors will take their situation into account. | testimony ] [ I've offered lengthy repayment plans, reduced or waived interest or late fees, or partial settlement for those explain their hardship. | testimony ] [ But if a debtor is uncooperative or doesn't respond to our attempts to work out a balance, what other alternatives do creditors have? | value ]

Example 9:

###Input: [ I have been falsely subserved twice. ] [ Both times resulted in verdicts against me. ] [ Thank you for taking the time to express your viewpoint, which should carry a LOT OF WEIGHT ] [ since you are in it at the ground level. ] [ If I had not been falsely subserved, it is possible that the debt collector would have been more humbled and more amenable to my extremely generous offer of agreeing to the pay the debt in full based on what it was at the time of the default, as long as I could start with a very low monthly payment and build it up over time. ] [ And as along as I was honoring my word, the debt would no longer be reported negatively on my credit report. ] [ But I never got that far ] [ because the debt collection companies simply hired someone who would deliver a service, no questions asked as to its legality. ]

###Output: [ I have been falsely subserved twice. | testimony ] [ Both times resulted in verdicts against me. | testimony ] [ Thank you for taking the time to express your viewpoint, which should carry a LOT OF WEIGHT | policy ] [ since you are in it at the ground level. | value | Thank you for taking the time to express your viewpoint, which should carry a LOT OF WEIGHT ] [ If I had not been falsely subserved, it is possible that the debt collector would have been more humbled and more amenable to my extremely generous offer of agreeing to the pay the debt in full based on what it was at the time of the default, as long as I could start with a very low monthly payment and build it up over time. | value ] [ And as along as I was honoring my word, the debt would no longer be reported negatively on my credit report. | value ] [ But I never got that far | testimony ] [ because the debt collection companies simply hired someone who would deliver a service, no questions asked as to its legality. | testimony | But I never got that far ]

Example 10:

###Input: [ The agency needs to be careful of new rules that will, though unintended, be harmful to the free market. ] [ However, it is important that litigation is monitored to ensure that the system does not allow reward with no risk. ] [ A plaintiff in a lawsuit cannot be placed in a situation where it is rewarding to sue with insufficient cause and minimal risk. ] [ Creditors and those following in the process of recovery do not need additional regulation in this area ] [ since their efforts are monitored by the CFPB. ] [ The CFPB does not need to set standards for the industry, ] [ but make it clear that only those documents provided to the court in the original filing will be considered in a CFPB review. ] [ If in the course of a CFPB review, it is found that litigation was filed without a successful verification of the facts, the CFPB could award the amount sought by the filing to the defendant of the case and a fine to the CFPB of no less than $2,000 but no more than the amount sought. ] [ This position would motivate the litigant to ensure their facts were correct before any filing took place. ] [ This position would allow CFPB to review cases filed no matter how they were adjudicated by the involved court. ] [ This review could be conducted at CFPB offices ] [ since it only requires the original filings. ] [ This review could be initiated simply based on a complaint to the agency's offices. ] [ The penalty could be adjustable based on a variety of agency standards. ] [ I would have to take more time to consider when the plaintiff was not the original creditor or a member of the recovery industry, ] [ but, again, there must be a risk associated with the reward to stop nuisance suits. ]

###Output: [ The agency needs to be careful of new rules that will, though unintended, be harmful to the free market. | policy ] [ However, it is important that litigation is monitored to ensure that the system does not allow reward with no risk. | value ] [ A plaintiff in a lawsuit cannot be placed in a situation where it is rewarding to sue with insufficient cause and minimal risk. | fact ] [ Creditors and those following in the process of recovery do not need additional regulation in this area | value ] [ since their efforts are monitored by the CFPB. | fact | Creditors and those following in the process of recovery do not need additional regulation in this area ] [ The CFPB does not need to set standards for the industry, | value ] [ but make it clear that only those documents provided to the court in the original filing will be considered in a CFPB review. | policy ] [ If in the course of a CFPB review, it is found that litigation was filed without a successful verification of the facts, the CFPB could award the amount sought by the filing to the defendant of the case and a fine to the CFPB of no less than $2,000 but no more than the amount sought. | value ] [ This position would motivate the litigant to ensure their facts were correct before any filing took place. | value | If in the course of a CFPB review, it is found that litigation was filed without a successful verification of the facts, the CFPB could award the amount sought by the filing to the defendant of the case and a fine to the CFPB of no less than $2,000 but no more than the amount sought. ] [ This position would allow CFPB to review cases filed no matter how they were adjudicated by the involved court. | value | If in the course of a CFPB review, it is found that litigation was filed without a successful verification of the facts, the CFPB could award the amount sought by the filing to the defendant of the case and a fine to the CFPB of no less than $2,000 but no more than the amount sought. ] [ This review could be conducted at CFPB offices | value ] [ since it only requires the original filings. | value | This review could be conducted at CFPB offices ] [ This review could be initiated simply based on a complaint to the agency's offices. | value ] [ The penalty could be adjustable based on a variety of agency standards. | value ] [ I would have to take more time to consider when the plaintiff was not the original creditor or a member of the recovery industry, | value ] [ but, again, there must be a risk associated with the reward to stop nuisance suits. | value ]

### Real Data ###

###Input: {formatted_input}
  
### Output:

#NOTE: Only give the output in the same format. No unnecessary texts or explanations please.

"""            
        generated_text = generate_output(prompt)
        generated_text = generated_text.split("#NOTE: Only give the output in the same format. No unnecessary texts or explanations please.")[-1].strip()
        generated_text = generated_text.split("\n\n")[0].strip()
        # print (generated_text)
        print (f"--------------------------------------------------------------------------------------------------------\n")

        # decoding and evaluation steps

        decoded_true_output = joint_decode_anl(true_output)
        true_components = decoded_true_output[0]
        true_relations = decoded_true_output[1]

        decoded_predicted_output = joint_decode_anl(generated_text)
        pred_components = decoded_predicted_output[0]
        pred_relations = decoded_predicted_output[1]

        # print (f'True components:\n{true_components}\n')
        # print (f'Predicted components:\n{pred_components}\n')

        print (f'True output:\n{true_output}\n')
        print (f'Predicted output:\n{generated_text}\n')

        evaluator.add_single(true_components, true_relations, pred_components, pred_relations)

    results = evaluator.evaluate()
    print (results)

    output_dir = os.path.dirname(output_filename)
    if not os.path.exists(output_dir):
        os.makedirs(output_dir, exist_ok=True)

    with open(output_filename, 'w') as file:
        json.dump(results, file, indent=4)
    
examples = f"""

# Example 11:

###Input: [ It has been my experience that practices can vary greatly between various creditors who find it necessary to turn delinquent or defaulted debt over to a collection agnency. ] [ In my situation, little or no notification was given. ] [ At a minimum, a creditor should give specific information as to date and which company the debt is being assigned or sold to. ] [ Getting such a notice would help me understand that there is going to be a change with whom I would be communicating with going forward. ] [ The costs and expenses or problems that dad honors are collectors would have been giving those is miniscule compared to the problems cause by not giving notice. ] [ I would argue that they would actually save money in the long run like giving such notices. ] [ At a minimum, The information that should be clear that in the notice is (1) the date of when the debt would be turned over to collection agency; (2) the name address of the collection constant company to whom the doubt was assigned; and (3) specific formation about the debt collection company and a list of that company's "best practices", policies and procedures as to what the consumer can expect. ] [ It would be good if there could be a single-point-of-contact for this company as well as the supervisors and owner of the collection company. ] [ Collection agencies need to be forced to deal more forthrightly with consumers and be required to deal with greater transparency. ]

###Output: [ It has been my experience that practices can vary greatly between various creditors who find it necessary to turn delinquent or defaulted debt over to a collection agnency. | testimony ] [ In my situation, little or no notification was given. | testimony ] [ At a minimum, a creditor should give specific information as to date and which company the debt is being assigned or sold to. | policy ] [ Getting such a notice would help me understand that there is going to be a change with whom I would be communicating with going forward. | value | At a minimum, a creditor should give specific information as to date and which company the debt is being assigned or sold to. ] [ The costs and expenses or problems that dad honors are collectors would have been giving those is miniscule compared to the problems cause by not giving notice. | value | At a minimum, a creditor should give specific information as to date and which company the debt is being assigned or sold to. | I would argue that they would actually save money in the long run like giving such notices. ] [ I would argue that they would actually save money in the long run like giving such notices. | value | At a minimum, a creditor should give specific information as to date and which company the debt is being assigned or sold to. ] [ At a minimum, The information that should be clear that in the notice is (1) the date of when the debt would be turned over to collection agency; (2) the name address of the collection constant company to whom the doubt was assigned; and (3) specific formation about the debt collection company and a list of that company's "best practices", policies and procedures as to what the consumer can expect. | policy ] [ It would be good if there could be a single-point-of-contact for this company as well as the supervisors and owner of the collection company. | value ] [ Collection agencies need to be forced to deal more forthrightly with consumers and be required to deal with greater transparency. | policy ]

# Example 12:

###Input: [ There's no need to be rude about it. ] [ There are some debt collection practices that should obviously be illegal. ] [ Other things that people are discussing here are obviously matters of convenience. ] [ To the extent that preferences are widely shared and outright prohibition wouldn't increase lending costs across the board beyond a marginal amount, outright prohibition makes sense. ] [ But if someone wants the ability to stop someone from conducting any and all robocalls from all phones, and robocalls help creditors recoup their loans, then the creditor should be able to charge a regulated fee for that convenience. ] [ I'm not saying that the debt collection agency itself would charge the fee ] [ Just that a consent-based approach is another option. ]

###Output: [ There's no need to be rude about it. | value ] [ There are some debt collection practices that should obviously be illegal. | value ] [ Other things that people are discussing here are obviously matters of convenience. | value ] [ To the extent that preferences are widely shared and outright prohibition wouldn't increase lending costs across the board beyond a marginal amount, outright prohibition makes sense. | value ] [ But if someone wants the ability to stop someone from conducting any and all robocalls from all phones, and robocalls help creditors recoup their loans, then the creditor should be able to charge a regulated fee for that convenience. | policy ] [ I'm not saying that the debt collection agency itself would charge the fee | fact ] [ Just that a consent-based approach is another option. | value ]

# Example 13:

###Input: [ Someone who lived at my address, more than 30 years ago had a debt with Household Finance. We get letters that we return "Addressee Unknown" and phone calls. Finally I called one number back and told them that the person they looked for wasn't there. That law firm stopped robo-calling ] [ but a few months later a new one started up. ] [ Records should convey when debts are sold from collection agency to collection agency. ] [ Why should I have to go through all that a second time? ] [ I also think debt collectors should be prohibited from using the address to get a phone number after 2 years. ] [ This debt was more than 30 years old ] [ why do they think anyone who knew here would still live there? ] [ I googled the woman's name. ] [ I found out on the first search that she lives about 10 miles from here. ] [ If I can find her that easily why can't a debt collector, who stands to gain something, be bothered to do a little research? ]

###Output: [ Someone who lived at my address, more than 30 years ago had a debt with Household Finance. We get letters that we return "Addressee Unknown" and phone calls. Finally I called one number back and told them that the person they looked for wasn't there. That law firm stopped robo-calling | testimony | Records should convey when debts are sold from collection agency to collection agency. ] [ but a few months later a new one started up. | testimony ] [ Records should convey when debts are sold from collection agency to collection agency. | policy ] [ Why should I have to go through all that a second time? | value | Records should convey when debts are sold from collection agency to collection agency. ] [ I also think debt collectors should be prohibited from using the address to get a phone number after 2 years. | policy ] [ This debt was more than 30 years old | testimony | I also think debt collectors should be prohibited from using the address to get a phone number after 2 years. | why do they think anyone who knew here would still live there? ] [ why do they think anyone who knew here would still live there? | value | I also think debt collectors should be prohibited from using the address to get a phone number after 2 years. ] [ I googled the woman's name. | testimony ] [ I found out on the first search that she lives about 10 miles from here. | testimony ] [ If I can find her that easily why can't a debt collector, who stands to gain something, be bothered to do a little research? | value ]

# Example 14:

###Input: [ banks can simply add this provision to their Loan Sale Agreements. ] [ All buyers executing a Loan Sale Agreement containing such a provision would be contractually obligated to refrain from litigating or threatening litigation. ] [ some current buyer would refuse to purchase with such a provision ] [ and other current buyers would expect a price discount ] [ because they woudl not be able to sue. ] [ In both instances, any inventory not acquired by current buyers would be quicly snapped up by other purchasors who would be willing to comply with these contractual provisions. ] [ Such a resolution would obviate the necessity of legislation or regulation ] [ as the matter woudl have been taken care of under the contract between a willing seller and a willing buyer. ] [ there would be no constitutional question regarding the restricting of law suits ] [ nor would there be any delay in implementation. ] [ All that would be required is the cooperation of the selling banks ] [ which could be induced readily with some Safe-Harbor language for banks that follow this protocol. ]

###Output: [ banks can simply add this provision to their Loan Sale Agreements. | fact ] [ All buyers executing a Loan Sale Agreement containing such a provision would be contractually obligated to refrain from litigating or threatening litigation. | value ] [ some current buyer would refuse to purchase with such a provision | value ] [ and other current buyers would expect a price discount | value ] [ because they woudl not be able to sue. | value | and other current buyers would expect a price discount ] [ In both instances, any inventory not acquired by current buyers would be quicly snapped up by other purchasors who would be willing to comply with these contractual provisions. | value ] [ Such a resolution would obviate the necessity of legislation or regulation | value ] [ as the matter woudl have been taken care of under the contract between a willing seller and a willing buyer. | value | Such a resolution would obviate the necessity of legislation or regulation ] [ there would be no constitutional question regarding the restricting of law suits | value ] [ nor would there be any delay in implementation. | value ] [ All that would be required is the cooperation of the selling banks | value ] [ which could be induced readily with some Safe-Harbor language for banks that follow this protocol. | value ]

# Example 15:

###Input: [ I have a fairly common last name, ] [ and my listing in the phone book uses two initials rather than a first name. ] [ I get calls from credit collectors several times a week looking for various people with my last name and one or the other of my two initials. ] [ They are just taking a stab in the dark. ] [ When I tell them that I don't live with any other family members and that I have an excellent credit rating, they take me off of their list to of numbers for today's person of interest. ] [ When I ask them not to call me at all because I have no other people living with me that they would be looking for, they say that they only had me listed for their person of the day. ] [ Tomorrow my number might pop up as a possibility for tomorrow's person of the day, but they "can't do anything about tomorrow." ] [ I actually had a credit collection rep (in India) say that to me. ]

###Output: [ I have a fairly common last name, | value ] [ and my listing in the phone book uses two initials rather than a first name. | testimony ] [ I get calls from credit collectors several times a week looking for various people with my last name and one or the other of my two initials. | testimony ] [ They are just taking a stab in the dark. | value ] [ When I tell them that I don't live with any other family members and that I have an excellent credit rating, they take me off of their list to of numbers for today's person of interest. | testimony ] [ When I ask them not to call me at all because I have no other people living with me that they would be looking for, they say that they only had me listed for their person of the day. | testimony ] [ Tomorrow my number might pop up as a possibility for tomorrow's person of the day, but they "can't do anything about tomorrow." | testimony ] [ I actually had a credit collection rep (in India) say that to me. | testimony ]

Example 16:

###Input: [ I am a clerk at a local city court. ] [ I am the civil clerk ] [ and I feel that debtors are treated extremely unfairly by debt collection laws. ] [ The Court cannot give legal advice ] [ so it is saddening to have to try and explain and console upset litigants who have no idea what they are in for. ] [ I think there should be more avenues for pro se litigants who cannot afford to retain a private attorney ] [ (which is 95 % of the litigants in my city). ] [ I can say that most people do not answer summonses because they either were not properly served or they just straight up do not care, or most often, do not understand the legalese. ] [ BUT, I do have to say that I get many litigants who call and ask what they do now that they are served. ] [ On the occasions that people do file answers, most of them are in letter form, not a "legal" verified answer. ] [ Most debt collection attorneys jump right on that and request a summary judgment. ] [ Our Court does not turn away letters, ] [ and we send a copy to the attorney and set the matter up for a pre trial conference with a judge or court attorney to help try to get both parties together to come to some sort of resolution. ] [ The Court does have to adhere to a scheduling policy for these conferences, ] [ but we are very flexible ] [ if a defendant has a scheduling conflict we try to accommodate them as best we can. ] [ When summonses are filed with the court, half of them have tons of information about the debt, others only have the amount due! ] [ I find that sometimes it's hard for litigants to obtain further proving documents from attorneys, even with the court telling them they have to. ] [ When entering default judgments, I take my time and examine the whole file, like comparing the contents of the summons/complaint and the default judgment submitted, re-checking the affidavit of service of the summons (to make sure the defendant had the legal time to answer the summons), and ensuring that attached to the default judgment is the proper documentation as to purchasing the debt, a non-military affidavit, etc. ] [ I also make sure that they are being charged the proper interest rate and court costs. ] [ The bottom line is that the debtors still do not have enough and/or sufficient laws to protect them, and the Court's hands are tied based on these laws, ] [ even if they wanted to help, they couldn't. ] [ I know the Court is to remain impartial, but in a small city, everybody knows everybody and sometimes it's hard to see these practices occurring. ]

###Output: [ I am a clerk at a local city court. | testimony ] [ I am the civil clerk | testimony ] [ and I feel that debtors are treated extremely unfairly by debt collection laws. | value ] [ The Court cannot give legal advice | fact | so it is saddening to have to try and explain and console upset litigants who have no idea what they are in for. ] [ so it is saddening to have to try and explain and console upset litigants who have no idea what they are in for. | value ] [ I think there should be more avenues for pro se litigants who cannot afford to retain a private attorney | policy ] [ (which is 95 % of the litigants in my city). | fact ] [ I can say that most people do not answer summonses because they either were not properly served or they just straight up do not care, or most often, do not understand the legalese. | fact ] [ BUT, I do have to say that I get many litigants who call and ask what they do now that they are served. | testimony ] [ On the occasions that people do file answers, most of them are in letter form, not a "legal" verified answer. | testimony ] [ Most debt collection attorneys jump right on that and request a summary judgment. | fact ] [ Our Court does not turn away letters, | testimony ] [ and we send a copy to the attorney and set the matter up for a pre trial conference with a judge or court attorney to help try to get both parties together to come to some sort of resolution. | testimony ] [ The Court does have to adhere to a scheduling policy for these conferences, | fact ] [ but we are very flexible | value ] [ if a defendant has a scheduling conflict we try to accommodate them as best we can. | value ] [ When summonses are filed with the court, half of them have tons of information about the debt, others only have the amount due! | fact ] [ I find that sometimes it's hard for litigants to obtain further proving documents from attorneys, even with the court telling them they have to. | value ] [ When entering default judgments, I take my time and examine the whole file, like comparing the contents of the summons/complaint and the default judgment submitted, re-checking the affidavit of service of the summons (to make sure the defendant had the legal time to answer the summons), and ensuring that attached to the default judgment is the proper documentation as to purchasing the debt, a non-military affidavit, etc. | testimony ] [ I also make sure that they are being charged the proper interest rate and court costs. | testimony ] [ The bottom line is that the debtors still do not have enough and/or sufficient laws to protect them, and the Court's hands are tied based on these laws, | value | even if they wanted to help, they couldn't. ] [ even if they wanted to help, they couldn't. | value ] [ I know the Court is to remain impartial, but in a small city, everybody knows everybody and sometimes it's hard to see these practices occurring. | value ]

Example 17:

###Input: [ Let's remember that most debtors have had the original creditor from 2 to 4 collection agencies and the creditors attorneys office before a suit is ever filed. That process usually takes as much a 2 years or more. ] [ So it is difficult to think that the courts should make special accommodations for these individuals. ] [ Every person called into court has had many opportunities to have the debt validated or payment arrangements made prior to a default judgment. ] [ I do believe basic evidence should be supplied. ] [ This would be a statement or bill copy with a matching name of the consumer and proof of address at the time the debt was incurred. ] [ This proof of address could be provided by other confirming data available through skip tracing companies. ] [ There were significant problems with how debt buyers were allowed to file suit and receive default judgments with virtually no evidence. ] [ So improvements and consistency is needed in evidence but it should also not be expected to show every single bill copy. ]

###Output: [ Let's remember that most debtors have had the original creditor from 2 to 4 collection agencies and the creditors attorneys office before a suit is ever filed. That process usually takes as much a 2 years or more. | fact | So it is difficult to think that the courts should make special accommodations for these individuals. | Every person called into court has had many opportunities to have the debt validated or payment arrangements made prior to a default judgment. ] [ So it is difficult to think that the courts should make special accommodations for these individuals. | value ] [ Every person called into court has had many opportunities to have the debt validated or payment arrangements made prior to a default judgment. | value | So it is difficult to think that the courts should make special accommodations for these individuals. ] [ I do believe basic evidence should be supplied. | policy ] [ This would be a statement or bill copy with a matching name of the consumer and proof of address at the time the debt was incurred. | value ] [ This proof of address could be provided by other confirming data available through skip tracing companies. | value ] [ There were significant problems with how debt buyers were allowed to file suit and receive default judgments with virtually no evidence. | value | So improvements and consistency is needed in evidence but it should also not be expected to show every single bill copy. ] [ So improvements and consistency is needed in evidence but it should also not be expected to show every single bill copy. | policy ]

Example 18:

###Input: [ I left a long comment about one particular collector, but recently was harassed by yet another one who was trying to collect from someone else who was not me. ] [ Their caller ID was not a phone number; ] [ it was just the names of different states, but turned out to be the same company. ] [ These people are bottom-feeders with no scruples. ] [ Accurate caller ID should be required ] [ so the victim can at least identify the collector and have a call-back number for them. ] [ And monetary penalties should be much, much stiffer to discourage their outrageous, predatory and harassing practices. ] [ Harrassment is part of their business models. ] [ These people are scum and should be required at the very least to identify themselves accurately. ] [ Robo-calls and ID spoofing should be illegal with stiff fines. ]

###Output: [ I left a long comment about one particular collector, but recently was harassed by yet another one who was trying to collect from someone else who was not me. | testimony ] [ Their caller ID was not a phone number; | testimony ] [ it was just the names of different states, but turned out to be the same company. | testimony ] [ These people are bottom-feeders with no scruples. | value ] [ Accurate caller ID should be required | policy ] [ so the victim can at least identify the collector and have a call-back number for them. | fact | Accurate caller ID should be required ] [ And monetary penalties should be much, much stiffer to discourage their outrageous, predatory and harassing practices. | policy ] [ Harrassment is part of their business models. | value ] [ These people are scum and should be required at the very least to identify themselves accurately. | policy ] [ Robo-calls and ID spoofing should be illegal with stiff fines. | policy ]

Example 19:

###Input: [ Consumers generally have no notice and do not know that a debt has been sold until checking their credit report or until a collection agency calls to collect a debt. ] [ Being notified of a debt being sold, would at least allow the consumer to verify who is actually the owner of a debt. ] [ I once paid a debt to a collection agency, only to find that I had paid one of 3 collection agencies who claimed to own the debt). ] [ With regards to costs, most consumers and most debt buyers are unable to detail how a 2200.00 debt becomes a 7000.00+ debt. ] [ And I found that very few even knew the original creditor's name, yet still attempted to collect this debt. ] [ The new rule should at minimum state the Original Creditor's name, and that Debt Buyer has purchased the right to collect the debt. ] [ This would allow the consumer to verify that a debt buyer has the right to collect the debt. ]

###Output: [ Consumers generally have no notice and do not know that a debt has been sold until checking their credit report or until a collection agency calls to collect a debt. | value ] [ Being notified of a debt being sold, would at least allow the consumer to verify who is actually the owner of a debt. | value ] [ I once paid a debt to a collection agency, only to find that I had paid one of 3 collection agencies who claimed to own the debt). | testimony ] [ With regards to costs, most consumers and most debt buyers are unable to detail how a 2200.00 debt becomes a 7000.00+ debt. | value ] [ And I found that very few even knew the original creditor's name, yet still attempted to collect this debt. | testimony ] [ The new rule should at minimum state the Original Creditor's name, and that Debt Buyer has purchased the right to collect the debt. | policy ] [ This would allow the consumer to verify that a debt buyer has the right to collect the debt. | value | The new rule should at minimum state the Original Creditor's name, and that Debt Buyer has purchased the right to collect the debt. ]

Example 20:

###Input: [ Give Consumers Fair Notice and A Chance to Bid on Their Own Debts When Banks Sell Defaulted Obligations to Debt Buyers ] [ When a consumer falls behind on loan or credit card payments, the bank often "sells" the account to a debt buying company for a few pennies on the dollar. ] [ Debt buyers contribute nothing to society. Yet, they are allowed to obtain windfall profits by pursuing impoverished consumers for the full face value of such debts. ] [ This is unfair. ] [ If a bank is going to sell a consumer"s debt for pennies on the dollar, the bank should be required to notify that consumer, and allow that consumer a fair chance to bid on and purchase his/her own debt, on terms just as favorable as the terms offered to any other debt buyer. ] [ I hope the CFPB will consider new rules in this regard. ] [ Please note there is currently a petition on the White House website for this issue at: ] [ __URL__ ] [ It was initiated here: ] [ __URL__ ]

###Output: [ Give Consumers Fair Notice and A Chance to Bid on Their Own Debts When Banks Sell Defaulted Obligations to Debt Buyers | policy ] [ When a consumer falls behind on loan or credit card payments, the bank often "sells" the account to a debt buying company for a few pennies on the dollar. | fact ] [ Debt buyers contribute nothing to society. Yet, they are allowed to obtain windfall profits by pursuing impoverished consumers for the full face value of such debts. | value | This is unfair. ] [ This is unfair. | value ] [ If a bank is going to sell a consumer"s debt for pennies on the dollar, the bank should be required to notify that consumer, and allow that consumer a fair chance to bid on and purchase his/her own debt, on terms just as favorable as the terms offered to any other debt buyer. | policy ] [ I hope the CFPB will consider new rules in this regard. | value ] [ Please note there is currently a petition on the White House website for this issue at: | fact ] [ __URL__ | reference ] [ It was initiated here: | fact ] [ __URL__ | reference ]

"""

